"""Independent durability/wire/accounting oracles; all runtime boundaries are scratch fakes."""

import json
import os
import stat
from pathlib import Path

import pytest
from test_recovery_orchestration import approve, command, execute, plan
from test_recovery_orchestration import fixture as fixture

from niri_desktop_continuity import recovery, store
from niri_desktop_continuity.model import digest
from niri_desktop_continuity.recovery_ledger import Ledger
from niri_desktop_continuity.recovery_protocol import LIMIT, decode, decode_frame, encode


def test_directory_and_record_sync_order_handwritten_oracle(tmp_path, monkeypatch):
    events = []
    mkdir, fsync = os.mkdir, os.fsync

    def create(path, *args, **kwargs):
        result = mkdir(path, *args, **kwargs)
        events.append(("mkdir", Path(path)))
        return result

    def sync(fd):
        path = Path(os.readlink(f"/proc/self/fd/{fd}"))
        kind = "sync-dir" if stat.S_ISDIR(os.fstat(fd).st_mode) else "sync-file"
        events.append((kind, path))
        return fsync(fd)

    monkeypatch.setattr(os, "mkdir", create)
    monkeypatch.setattr(os, "fsync", sync)
    root = tmp_path / "ancestor" / "nested" / "canonical"
    ledger = store.Store(root)
    ledger.recovery_marker("recovery-prepared", "a" * 64, {"fabricated": True})
    events.append(("dispatch", None))
    # Literal names/order contract, not generated by Store's helper or KINDS.
    created = {tmp_path / "ancestor", tmp_path / "ancestor/nested", root}
    created |= {
        root / name
        for name in (
            "snapshots",
            "plans",
            "approvals",
            "used",
            "receipts",
            "previews",
            "recovery-prepared",
            "recovery-ready",
            "recovery-terminal",
            "recovery-events",
        )
    }
    assert {path for kind, path in events if kind == "mkdir"} == created
    first_file = next(i for i, event in enumerate(events) if event[0] == "sync-file")
    for directory in created:
        index = events.index(("mkdir", directory))
        assert events[index + 1 : index + 3] == [
            ("sync-dir", directory),
            ("sync-dir", directory.parent),
        ]
        assert index + 2 < first_file
        if directory.parent in created:
            assert events.index(("mkdir", directory.parent)) + 2 < index
    path = root / "recovery-prepared" / ("a" * 64 + ".json")
    assert events[-3:] == [("sync-file", path), ("sync-dir", path.parent), ("dispatch", None)]
    assert all(p.stat().st_mode & 0o777 == 0o700 for p in created)


def test_directory_fsync_failure_prevents_execute(fixture, monkeypatch):
    data = fixture()
    approval = approve(data, plan(data))
    root = data["root"] / "ledger"
    # Owned empty scratch directory only; simulate a newly provisioned fence directory.
    (root / "recovery-ready").rmdir()
    original = store.sync_directory

    def fail_parent(path):
        if path == root and (root / "recovery-ready").exists():
            raise OSError("fabricated directory sync failure")
        original(path)

    monkeypatch.setattr(store, "sync_directory", fail_parent)
    with pytest.raises(ValueError):
        execute(data, approval)
    assert not (data["root"] / "effects.jsonl").exists()
    assert '"execute"' not in (data["root"] / "phases.jsonl").read_text()
    assert not list((root / "recovery-prepared").iterdir())


def test_unsafe_directory_never_repaired(tmp_path):
    unsafe = tmp_path / "unsafe"
    unsafe.mkdir(mode=0o755)
    with pytest.raises(ValueError):
        store.Store(unsafe)
    assert unsafe.stat().st_mode & 0o777 == 0o755
    link = tmp_path / "link"
    link.symlink_to(unsafe, target_is_directory=True)
    with pytest.raises(ValueError):
        store.Store(link / "new")
    assert not (unsafe / "new").exists()


@pytest.mark.parametrize(
    "raw",
    [
        '{"x":1}'.encode("utf-16"),
        '{"x":1}'.encode("utf-32"),
        b'{"x":"\xff"}',
        b'{"x":1e309}',
        b'{"x":-1e309}',
        b'{"x":NaN}',
        b'{"x":Infinity}',
        b'{"x":1,"x":2}',
        b"{}{}",
        b"{}\n{}",
    ],
)
def test_strict_json_encoding_and_numbers(raw):
    with pytest.raises(ValueError):
        decode(raw)


def test_exact_wire_limit_excludes_only_framing_lf():
    raw = b"{}" + b" " * (LIMIT - 2)
    assert len(raw) == 1048576
    assert decode(raw) == decode_frame(raw + b"\n") == {}
    assert decode(b'{"x":1e308}')["x"] == 1e308
    with pytest.raises(ValueError):
        decode_frame(raw + b" \n")
    with pytest.raises(ValueError):
        decode_frame(raw)  # no terminal LF
    with pytest.raises(ValueError):
        decode_frame(raw + b"\n\n")  # only ONE LF is excluded from size
    value = {"x": "a" * (LIMIT - 8)}
    assert len(encode(value)) == LIMIT + 1
    assert decode_frame(encode(value)) == value


def test_torn_other_attempt_does_not_hide_target_intent(fixture):
    data = fixture(mode="die-after-intent")
    approval = approve(data, plan(data))
    execute(data, approval)
    ledger = Ledger(data["profile"])
    terminal = ledger.store.path("recovery-terminal", approval)
    terminal.write_text("{")
    other = ledger.store.path("recovery-prepared", "0" * 64)
    other.write_text("{")
    other.chmod(0o600)
    before = {path: path.read_bytes() for path in (terminal, other)}
    inspected, status = command(data, "inspect", approval, "--kind", "reconstruction")
    assert status == 2 and inspected["status"] == "indeterminate"
    assert {item["attempt_digest"]: item["accounting"] for item in inspected["canonical"]} == {
        approval: "invalid-or-unreadable",
        "0" * 64: "invalid-or-unreadable",
    }
    intent = inspected["interruption_evidence"][0]
    assert intent["intent"]["intent_ref"] == "1" * 64
    assert intent["intent"]["kind"] == "shutdown" and intent["outcome"] == "unresolved"
    assert intent["accounting"] == {"intent": "valid", "result": "missing"}
    assert inspected["event_scan"]["absence_is_no_effects_proof"] is False
    assert inspected["retry_authorized"] is False
    assert {path: path.read_bytes() for path in before} == before
    with pytest.raises(ValueError):
        command(data, "verify", approval, "--kind", "reconstruction")
    with pytest.raises(ValueError):
        ledger.available()


def test_event_diagnostics_validate_each_record_independently(fixture):
    data = fixture()
    approval = approve(data, plan(data))
    execute(data, approval)
    ledger = Ledger(data["profile"])
    index = digest({"attempt_digest": approval, "sequence": 0, "event": "intent"})
    ledger.store.path("recovery-events", index).write_text('{"private":"FABRICATED-SECRET"}')
    inspected, _ = command(data, "inspect", approval, "--kind", "reconstruction")
    record = inspected["interruption_evidence"][0]
    assert "intent" not in record and record["result"]["outcome"] == "observed"
    assert record["accounting"]["intent"] == "invalid-or-unreadable"
    assert record["outcome"] == "unresolved"
    assert len(inspected["interruption_evidence"]) == 3
    assert "FABRICATED-SECRET" not in json.dumps(inspected)


def test_missing_accounting_directory_is_not_recreated(fixture):
    data = fixture(mode="die-after-intent")
    approval = approve(data, plan(data))
    execute(data, approval)
    root = data["root"] / "ledger"
    (root / "recovery-terminal" / (approval + ".json")).unlink()
    (root / "recovery-terminal").rmdir()
    inspected = recovery.inspect_or_verify(store.Store(data["root"] / "state"), approval)
    assert inspected["status"] == "indeterminate"
    assert not (root / "recovery-terminal").exists()
    assert inspected["canonical_scan"]["scan"] == "unknown"
    assert inspected["interruption_evidence"][0]["intent"]["kind"] == "shutdown"


def test_missing_plan_still_allows_safe_diagnostics(fixture):
    data = fixture(mode="die-after-intent")
    key = plan(data)
    approval = approve(data, key)
    execute(data, approval)
    (data["root"] / "ledger/plans" / (key + ".json")).unlink()
    inspected, code = command(data, "inspect", approval, "--kind", "reconstruction")
    assert code == 2 and inspected["plan_accounting"] == "unknown"
    assert inspected["adapter"] is None and inspected["adapter_accounting"] == "unknown"
    assert inspected["interruption_evidence"][0]["intent"]["kind"] == "shutdown"
    assert inspected["retry_authorized"] is False


def test_unreadable_event_does_not_hide_independent_intent(fixture):
    data = fixture()
    approval = approve(data, plan(data))
    execute(data, approval)
    ledger = Ledger(data["profile"])
    result = ledger.read_event(approval, 0, "result")
    # Unsafe permission is rejected even though the owner could physically read it.
    path = ledger.store.path("receipts", result["receipt_digest"])
    path.chmod(0o644)
    inspected, code = command(data, "inspect", approval, "--kind", "reconstruction")
    assert code == 2
    record = inspected["interruption_evidence"][0]
    assert record["intent"]["kind"] == "shutdown" and "result" not in record
    assert record["accounting"]["result"] == "invalid-or-unreadable"
    assert path.stat().st_mode & 0o777 == 0o644  # no permission repair


def test_unknown_canonical_entry_is_bounded_sanitized_unknown(fixture):
    data = fixture(mode="die-after-intent")
    approval = approve(data, plan(data))
    execute(data, approval)
    unknown = data["root"] / "ledger/recovery-ready/FABRICATED-SECRET"
    unknown.write_text("not-accounting")
    inspected, code = command(data, "inspect", approval, "--kind", "reconstruction")
    assert code == 2 and inspected["canonical_scan"]["scan"] == "unknown"
    assert "FABRICATED-SECRET" not in json.dumps(inspected)
    assert inspected["interruption_evidence"][0]["intent"]["kind"] == "shutdown"
    with pytest.raises(ValueError):
        command(data, "verify", approval, "--kind", "reconstruction")
